### PR TITLE
Fix repo screen and adjust layout

### LINKED ISSUE #12: リポジトリページの作り込み

### LINKED ISSUE #14: トップパネルの表示（検索結果画面への遷移で複数の値を渡す）

### PR DESCRIPTION
**Pull request by yoshixmk**
- [x] fix layout 
- [x] showing user info using GET req
- [x] find how to appear user's icon and more user info
- [x] change arrow back color

### CODE REVIEW

File: app/src/main/java/com/example/ghac/ui/UserRepoViewModel.kt [hunk 1]
```diff
@@ -0,0 +1,60 @@
...
+            if (!username.isNullOrEmpty() && _uiState.value is UiState.Loading) {
+                _uiState.value = UiState.Success(githubUserRepository.getGithubUser(username))
+            }
+        }
+    }
+
+    @OptIn(ExperimentalCoroutinesApi::class)
+    fun pagingFlow(username: String): Flow<PagingData<GithubRepo>> {
+        // should be better good idea
+        user(username)
```
Comment (yoshixmk) [inline app/src/main/java/com/example/ghac/ui/UserRepoViewModel.kt:52]: Call viewModelScope.launch on the first page only.  
It should be possible to write it as an independent process, but I couldn't find the solution.
